name: erdos-dl
channels:
  - pytorch
  - conda-forge
  - defaults

dependencies:
  # --- Core Environment ---
  - python=3.12.*

  # --- Data Science stack ---
  - numpy=1.26.*
  - pandas=2.2.*
  # … (unchanged) …

  # --- PyTorch CPU build ---
  - pytorch=2.3.*
  - torchvision=0.18.*
  - torchaudio=2.3.*
  - cpuonly

  # --- Validation / utilities ---
  - black
  - libcst
  - sympy
  - hypothesis
  - sentence-transformers

  # --- NEW: LLM provider SDKs installed with Conda, if available ---
  - anthropic>=0.21

  - pip                      # keep pip meta-package

  - pip:
      - vertexai[preview]          # <-- only pip-exclusive item
      - google-generativeai        # already present; keep pinned version
      - openai==1.35.*
      - httpx==0.27.2
      - datasets==2.20.*
      - transformers==4.45.*
      - tokenizers>=0.20
      - python-dotenv==1.0.*