name: erdos-dl
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  # --- Core Environment ---
  - python=3.12.*

  # --- Core Data Science & ML Libraries (Conda) ---
  - numpy=1.26.*
  - pandas=2.2.*
  - scikit-learn=1.5.*
  - matplotlib=3.9.*
  - seaborn=0.13.*
  - tqdm=4.66.*
  - jupyterlab=4.2.*
  - ipywidgets=8.1.*

  # --- PyTorch (Conda) ---
  - pytorch=2.3.*
  - torchvision=0.18.*
  - torchaudio=2.3.*
  - cpuonly # Keep this if you are not using an NVIDIA GPU

  # --- Additional packages for validation ---
  - black
  - libcst
  - sympy
  - hypothesis
  - sentence-transformers

  # --- Pip for packages not prioritized on Conda ---
  - pip

  # --- Python packages to be installed with Pip ---
  - pip:
      - google-generativeai
      - anthropic
      - openai==1.35.*
      - httpx==0.27.2
      - datasets==2.20.*
      - transformers==4.45.*
      - tokenizers>=0.20
      - python-dotenv==1.0.*