lines_without_eqn = ['The second hundred years’ ship had twice as many as the first, so it had 2S people.',
 'According to the ratio, for every 5 parts that Johnson gets, Mike gets 2 parts',
 'Her income was increased by $600 so it is now p+$600',
 '15 coins collected in hour one',
 '35 coins collected in hour two',
 '35 coins collected in hour three',
 '50 coins collected in hour four',
 'Lee earned $558 mowing lawns last week.',
 'The last two people each lost 28 kilograms of weight.',
 'Last year: 86 geckos',
 'Janice had X sentences from yesterday already typed to start with today.',
 'She has 2 bills to mail.',
 'Jayden is 4 years old.',
 'Keiko sent 283 texts last week and this week combined.',
 'So this movie is 192 minutes',
 'Dallas is 46 years old now.',
 'He ate 70 apples in total.',
 'We let x be the amount of money she put in the bank the first year,',
 'Then the second year was 2*x,',
 'Bekah needs to read 59 pages each day.',
 'There are 2280 pieces of fruit in total.',
 'Thus, the length of a long side of the fence is 3S.',
 'There are 3 bouquets.',
 'An hour has 60 minutes.',
 'Fords:3+2x',
 'He therefore needs to buy 5 bags of flour because 4 < 4.8 < 5',
 'He spends $50 if he buys the cheapest flour because 50 < 52',
 'She spends 8*7-56 hours sleeping.',
 'Cows:4+x',
 'Therefore a dozen apples should cost $2',
 'Sam completes a widget every 10 minutes.',
 'When Jack helps they finish 2 in 15 minutes. Sam has finished 1 widget and has begun working on another one, and Jack finishes the second one at 15 minutes. So it takes Jack 15 minutes to complete a widget.',
 'Day 1:50',
 'Together they skip 150 times a minute.',
 'Then the number of games Carla won would be 2*x.',
 "He gets paid $10,000 because that's how much he gets if he averages 30 or more points that week.",
 'So, he sold 18 kg of vegetables.',
 'She gives the boy she likes 10 stickers.',
 "We'll assume the number of marbles that Elliot has is x.",
 'For the 30-day pass to be cheaper, then the average fare should be cheaper than the $2 one-way ticket.',
 'She hiked 24 miles.',
 'She spent 6 hours hiking.',
 '7 leaves fell in the first hour.',
 '4 leaves fell in the second hour.',
 '4 leaves fell in the third hour.',
 'In ten years, my brother will be (X+10)*1/2 years old.',
 'Bianca, Celeste and McClain worked a total of 3240 minutes last weekend.',
 'Jackson has 5*x dollars.',
 'Gracie is 56 inches tall.',
 'We calculate 50% of 16 GB:',
 'Melanie starts with 1 slice of bread that she tears in half, making 2 halves.',
 'In 2 minutes, 12 liters of water flow into the bathtub and 2 liters (2 minutes x 1 liter/minute ) escape.',
 'Week 3:210 pages',
 'We know that Yolanda will spend a total of x + 15 minutes riding her bike since she left 15 minutes before her husband.',
 "The distance each person travels is equal to their travel speed times the number of minutes they spend traveling. That means Yolanda's distance is equal to 20 mph * (x + 15) and her husband's distance is equal to 40 mph * x",
 'Going by the ratio, for every 1 part that Amy gets, Sandra will get 2 parts',
 'They still have 121 miles to travel.',
 'They worked a total of 40 hours.',
 'The Chrysler Building has 23 floors.',
 'So, for yellow candies, there were 20 less than 120 candies, or a total of',
 'Together they walked 27 kilometers.',
 'Viviana has 20 Vanilla chips.',
 'Susana has 25 chocolate chips.',
 'He has 300 cents left at the end.',
 'There are 7 people on the bus after the first stop.',
 '11 passengers are now on the bus.',
 '232 square feet of shingles will be needed.',
 "Djibo's sister is 28 years old today.",
 "To get the number of people at Taylor's party, we'll assume there were n people at his party.",
 "The total number of people at Ryan's party is 4*n, four times the number of attendees at Taylor's party.",
 'Johann must deliver 98 pieces of mail.',
 'Then find the number of pages that are both blurred and crumpled by finding how many numbers are less or equal to 42 and divisible by both 3 and 7: there are two, 21 and 42.',
 'There are 52 strawberries in the crate.',
 'Bess produces 2 pails every day.',
 '20% of the people vaccinated were children. The number of children is 20% of 650.',
 'Geraldo drank 7 pints of tea.',
 'So by lunchtime, the remaining number of books will be 100-x',
 'After adding 40 more books, the total number of books increased to 100-x+40.',
 'The younger friend is X-2 years old.',
 'Mike received 3 oranges.',
 '1.000 grams is equal a 1 kilogram.',
 'James has 7+4x Oreos',
 'There are 3 bouquets.',
 'Paula wants to go on the go-kart 1 time and the bumper cars 4 times.',
 'There are 2C meerkats in the new exhibit.',
 'There are 33 ounces of cereal in those 3 boxes.',
 'Hezekiah is 4 years old.',
 'The two pieces of yarn have a length of 632 centimeters.',
 'Free response:x+7',
 'Mehki is 22 years old.',
 'There are 355 pairs of purple shoes in the warehouse.',
 'Mimi therefore spent 2600 dollars on clothes.',
 'Archie needs 245 square yards of sod.',
 'Tamara is 68 inches tall.',
 'Bowler 2:3x',
 'There are 60 minutes in an hour.',
 'Darla:6 books',
 'Thus, Sarah is the girl with the most total followers with a total of 180.',
 'He bought 12+5x pencils',
 'Thus, Brad’s zip code is 11026.',
 "If x is Maria's age, then Mario's age is x + 1.",
 'If n is the number of $20 bills then 2n is the number of $10 bills.',
 'If we let x be the total number of orange balls, we know that 3x is the number of pink balls',
 'The 3 people lost a total of 89 pounds.',
 "If the first 100 miles took one hour, then let's say the next 300 miles took x hours.",
 'Antoinette weighs 63 kilograms.',
 "Let's say the number of men working at the company is x.",
 'Since Connie spends half of her tickets on a stuffed koala bear, that means the 25 tickets she spent on earbuds and glow bracelets is the other half, so she spent 25 tickets on the stuffed koala bear.',
 'All the animals have 4 legs.',
 'Each school will receive 859 balloons.',
 'Amelia still has 6716 kilometers to drive.',
 "Let's assume the total amount of money that Jane has is m.",
 "Since 1 seed packet grows 3 plants, he'll need 1 more to make the plants 12.",
 'Keegan spends 72 minutes in one of his other classes.',
 'Jafari started with 76 pieces of candy.',
 'There are 88 pieces of candy left in the bowl.',
 'There are 7 yellow highlighters.',
 'The two boys drank a total of 36 cups of liquid yesterday.',
 'It rained 12 centimeters more on Tuesdays than on Mondays.',
 "Let's say Kamari has x toys. Anais has x + 30 toys.",
 'The winner rotated 404 objects because 404 > 400',
 'So let x be the original price.',
 'Hence, it took him 1/300 of an hour to finish the 1 kilometer.',
 'Kramer never found the pool and thus swam for 0 minutes.',
 'She will need to work 138 hours to pay all of her bills',
 'He has read 600 pages in total.',
 'Together they lost 35 pounds.',
 'Accordingly, the 40%-full tire needs 500 cubic inches * (100%-40%).',
 'And, the 70%-full tire needs 500 cubic inches * (100%-70%).',
 'The cost of the second house is 2C',
 'Tamika drove 85 miles farther.',
 'There are 3*x grape candies.',
 'Layla earned $273 for babysitting.',
 'The 1 snake has no paws, and a spider has 8 legs.',
 'Yoki picked up 10 cans.',
 "Let's say Rickey took t minutes to finish the race.",
 'Maria goes to the coffee shop twice a day.',
 'She spent X dollars on Friday.',
 'What is the total number of seeds in a watermelon?',
 'Since Hazel sold half her lemonade to a construction crew, that means the 28 cups she sold to kids on bikes, gave away to friends and drank herself are the other half, so she sold 28 cups to the construction crew.',
 'Woodwind:2x',
 'Vikki also pays $5 in union dues.',
 'There are 6 yellow marbles.',
 'Since the father is walking 3 times as fast as his son, their speeds are in a ratio of 3:1 respectively',
 'They started at the same time so they will cover distance at the same ratio of 3:1',
 'It took Felipe 30 months to build his house.',
 'The largest collection has 1,250 pages because 1,250 > 1,200',
 'He sold 2S systems on the second street.',
 'Before going on vacation, Grandpa counts 36 tomatoes.',
 'She fills it 1 time for the brown sugar because she needs exactly 1/4 of a cup',
 'There are 6284 flowers at the Greene Nursery.',
 'Selena ran 24 miles.',
 'If we let x be the amount of time, in hours, it will take for Darrel to catch up to the coyote, then we can figure this out.',
 "Because the distance Darrel travels is defined as the length of time Darrel travels (x) and Darrel's speed (20mph), or the expression 2*x.",
 "And the distance the coyote travels is defined as the length of time the coyote travels (x+1 hour) and the coyote's speed (15 mph), or the expression (x+1)*1.",
 'Number of hens:9x-5',
 'Since Thomas cannot buy half a can, he needs to buy 8 cans.',
 "Let's say Greg had x number of golds.",
 'The maestro is 1 person.',
 'The gardens have a total of 304 square feet.',
 'Jamal started with B books in the cart.',
 'He had B - 12 books after the history section.',
 'They are to order a total of 3 burger meals and 3 sodas for Paulo and Jeremy.',
 "Let's say Sabrina has p number of pencils.",
 'Cayugas:3+2x',
 'After the photo shoot, he had 71 + P photos.',
 'There are 5 school days in a week, so the probability Karen packs a ham sandwich is 3/5 and the probability she packs cake is 1/5',
 'Throughout the day, she used w-20 wet wipes.',
 'Red:14 crayons',
 'Seven white rhinos and 8 black rhinos would weigh 51,700 pounds.',
 "We are trying to figure out how many times Max won at Mario Kart, so we'll call that number Y.",
 "If Markus's son is twice the age of Markus's grandson, then Markus's son is 2*x.",
 'If Markus is twice the age of his son, then Markus is 2*2*x.',
 'Day 1:4',
 'They had 21 liters of fruit punch for the picnic.',
 'Anna has 3*x toys.',
 'Amanda has 3*x+2 toys.',
 'The first month she saved 10 dollars',
 'There are a total of 94 crayons.',
 'Renaldo and Ernesto drove a total of 27 kilometers.',
 'We have 60 minutes per hour.',
 'The volume of air inhaled is 13600 liters.',
 'There are 1591 voters in Districts 1 - 3.',
 "Let's say the river's length in the straight part of the river is x.",
 'Therefore, when Jeff took the break, he had 56 laps remaining',
 'Zoe therefore made 2600 dollars cleaning pools.',
 'Let’s use r for the cost of each necklace',
 'Together the friends walked 25332 feet.',
 'Together Javier and Sanda exercised for 620 minutes.',
 "If Ken goes from his house to Dawn's, he has covered 4 miles",
 'The fastest route takes 20 hours because 20 < 30',
 'Together they climbed 495 stairs yesterday.',
 "Let's say the age of Hakimi is x.",
 'Since Jared is 10 years older than Hakimi, Jared is x+10 years old.',
 'There are 86 black cars on the lot.',
 'The two rabbits will hop 135 meters in 5 minutes.',
 'Between 2:30 pm and 5:00 pm, there are 2.5 hours.',
 'The table costs 3*x.',
 'Kelsey watched 160 videos.',
 'Which left Mark with 28 buttons',
 'Eight servings would need 14 pints of vegetables and broth.',
 'That means he lifted a total of 352 kg',
 'The 3 children had 66 seashells altogether.',
 'Luca lost 81 kg more than Barbi.',
 'Starting with 120 pennies he has $1.20',
 'Thus, Madeline will need to buy 2 packs of flowers to have at least 40 seeds.',
 'Middle brother:x+1',
 'Oldest brother:x+2',
 'Natasha and Esteban exercised for a total of 5 hours.',
 'Billy Mountain and Mount Pilot received 326 more centimeters of snow than Bald Mountain.',
 '400 is the most he can buy because 400 is greater than 300',
 "Let's say Jason invested x amount of money.",
 'Each week has 7 days',
 'Jason spent 1/4*X + 10 on books.',
 'Jason spent 2/5*[X - (1/4*X + 10)] + 8 on some DVDs.',
 "If I give my brother 2 marbles, I'll have X-2 marbles left.",
 'And my brother will have (X-2)/2 marbles.',
 'And my friend will have (X-2)*3 left.',
 'Rebecca is A - 2 years old.',
 'Freddy is A + 4 years old.',
 'One week has 7 days.',
 'The 3 athletes ran 204 yards.',
 'Night 1:30 pages',
 'Kay 32 years old',
 'The kitchen is 265 square feet.',
 'Each of the remaining grandchildren would receive $6230.',
 'A dollar is 100 cents, so standard postage is 108 cents.',
 'Then the guest bedroom is 0.25x.',
 'Mohamed therefore donated an additional 7 toys.',
 "Each plate weighs 10 ounces, so the weight of the plates in the box after Hasan removes enough plates to satisfy the movers' weight limit is (38 - x) * 10 ounces",
 'If "x" is the number of European swallows, then, for every one European swallow, there would be 2x American swallows.',
 'The second chapter has P + 3 pages.',
 'If the time he lifts weights is x, then the time he runs is 2x.',
 'The 3 friends ate 64 ounces of fudge in total.',
 'Roger: 4x-7',
 'He can make 20 glasses of chocolate milk because 20 < 40',
 'Thus, the second runner can stop for a maximum of 8 minutes, which is the amount of time it takes the first runner to travel 1 mile.',
 'Four feet six inches is the same as 4.5 feet tall.',
 'The blue light bulb comes on every 2 seconds so it will be on after 2, 4, 6, 8, 10, 12, 14... seconds (multiples of 2)',
 'The shortest time after which all three will be on is 12 seconds which is the least common multiple of the set of multiples.',
 'She will get 2 quarters to account for $.50 of the change. She will also get 1 nickel to account for $.05 of the change. Then, she will get 1 penny, to account for the last $.01 of the change.',
 "If Tom can fold either the small or medium box in 4 seconds, then he's faster at folding the medium box than Hugo because 4s < 6s",
 "If Hugo can fold the small box in 3 seconds, then he's faster at folding the small boxes than Tom because 3s < 4s",
 'Therefore Hugo should fold all small boxes and Tom should fold all the medium ones before doing the other size where they are slower',
 'Given that they need the same amount of time to fold all boxes, and are doing it simultaneously they will need 7200 seconds to fold all the boxes',
 'Since 20<30, the apples are cheaper.',
 'The area of a square is calculated as length * width. Because all a square has all sides equal then we can say that given a side S, the area is S*S',
 'Nickels: x-6',
 'Dimes: x+3',
 'Peter is 10 years old because he has 10 birthday candles on his cake.',
 'Kathleen’s aunt did not give Kathleen any money because $112 is not greater than $125.',
 'KJ:x/2 stamps',
 'Then the length of the patio would be 4*x.',
 "They ran 1 minute faster per mile compared to last year's winner.",
 'Ken will therefore get 6 dollars back.',
 "For every 3 steps forward, he adds 2 more backwards so each 'step' gained costs 5 actual steps",
 "At Gustran salon she would spend $97, at Barbara's Shop she would spend $98, and at The Fancy Salon she would spend $84, so she would spend $84 at the cheapest salon.",
 'This calculation means that she takes 5 trips carrying 3 objects per trip, and then she takes one additional trip carrying only two objects.',
 'The passengers that paid at the gate paid $2900 more dollars than those who pre-bought their tickets.',
 'Now Radhika has 30 video games.',
 "Let's assume the number of female attendees is x.",
 'The number of male attendees is x+4.',
 'If one-third of the Pelicans in Shark Bite Cove move to Pelican Bay,',
 'In 5 weeks they will have equal money.',
 'You know from the statement that on Monday he sells 2 pastries, so on Tuesday he sells 3, Wednesday 4, Thursday 5, Friday 6, Saturday 7 and Sunday 8 pastries.',
 'If the pen costs 2 times the cost of the pencil, then it costs 2x.',
 "Let's say the number of Schnauzers is s.",
 'The difference between the number of Doberman puppies and the number of Schnauzers is s-20',
 'Clementine baked 72 cookies.',
 'Sally will need 5844 square inches of material to make the tablecloth and 8 napkins.',
 'Anya took 84 balloons home.',
 "The garbage truck passes through Daniel's neighborhood for 3 days.",
 'Greg spent 2x+9 dollars on shoes.',
 'Greg spent 97$ on a shirt.',
 'It would take 840 minutes to groom 5 dogs and 3 cats.',
 'There are approximately 4 weeks in a month.',
 'She sold 18 bikes within the same time frame',
 'The runner with the highest average speed is Tiffany because 2 > 1.5',
 'Drink Mix: 3x',
 'Bottles of Water: x+2',
 'Each pile has 10 coins, so he has:',
 'There are 35 apples in the box.',
 'Jasmine swims 5 days a week.',
 'Joe is 6+2x inches tall',
 'The students have 20 minutes to start.',
 'Thus, Mona biked 2M miles on Saturday.',
 'Jenny has 6 cards.',
 "Liz's opponents score 10 points during the quarter, meaning their lead is 30 points in total before accounting for Liz's scoring.",
 'Mr. Chiu has 56 silver dollars.',
 'Therefore, the maximum number of cheesecakes Lionel can make is 5.',
 'It took Ivanka and Woody 39 months to write their books.',
 '104 square meters of the playground are not covered by the maintenance building.',
 'One of the remaining units is 200 square feet.',
 'We change the writing of the equation:',
 'We then Remove 16 from both sides:',
 'Since the hypotenuse of a triangle is found by the square root of the base squared plus the height squared.',
 "Let's say Rhonda has m marbles.",
 "The adults' tickets cost $50 more than the children's tickets.",
 'Pitbull:3x',
 'Kirill is 49 centimeters tall.',
 'Find the price of each group of fruit',
 'The last part of the race is 16 kilometers.',
 'Each serving would be 8 ounces.',
 'Two weeks already passed and Bob has 200 dollars.',
 'Jupiter appears 2 hours and 41 minutes after 12:10 AM, which can be calculated in two parts;',
 'Uranus appears 3 hours and 16 minutes after 2:51 AM, which can be calculated in two parts:',
 'Because each child must receive the same number of slices, the total number of slices must be evenly divisible by 20.',
 'He gets 79 questions right in total.',
 'Right:2x',
 'Center:x+2',
 'In total there are 30 pages turned in by the students.',
 "Let's assume Dan's helmet has C craters.",
 "Dan's skateboarding helmet has 35 craters.",
 'Manny will eat 1 piece.',
 'Thus, Manny should cut his lasagna into 6 pieces.',
 'The first 7 days were $190.',
 'The playground and garden have a combined fence length of 150 yards.',
 'There are 52 weeks in a year.',
 'Marina had 14 more ounces of fudge than Lazlo.',
 'Casey owns H + 2 hoodies.',
 'If my original bet was X then I won 1.5*X my bet',
 'Since 168 < 182 and 224 > 182, Brittany needs 4 bottles of shampoo to get her through a leap year.',
 'She hit 200 drums to start making money',
 'If she takes away the remaining .75, each goat gets an even 11 carrots each.',
 'Remy used 25 gallons of water for his shower.',
 'Jaydon:5+2x',
 'Devin has been teaching for (1/2)x-5 years',
 'Tom has been teaching for 50 years',
 'Adah practiced a total of 278 minutes on the other days.',
 'It rained 2x+7 inches in the second hour.',
 'The price of the coat is X*3.',
 'On Monday Elisa paints 30 square feet of wall.',
 'The distance between Arizona and New York is 2,000 miles by plane.',
 'Dr. Banks gave 82 toothbrushes in his busiest month and 46 toothbrushes during the slowest month.',
 'The average jump of the winner was 22 feet because 22 > 21',
 'You save $5 per chair with the 25% off sale.',
 'Nine cheesecakes need 57 more eggs than 5 chocolate cakes.',
 'Stephanie is going to purchase 11 spoons, 11 butter knives, 10 steak knives, and 12 forks.',
 'Stephanie is going to purchase 44 pieces of silverware.',
 'There are 7 letters in Jessica.',
 'We know that the first 10 pens are sold at the regular price, so they cost 10*p.',
 'We also know the any pens purchased after the first 10 are half-price, so they cost (20 pens - 10 pens) * p/2 on those.',
 'Jessie scored 41 points.',
 'The other 5 pieces cost $96 each.',
 'Akeno spent $1172 more than Lev and Ambrocio combined.',
 'Amy:(1/3)x',
 'He then cycles 50 miles to Peter.',
 "Since you're doubling the number of people working on the task, that means you will be able to reduce the amount of time worked in half if they're of equal skill.",
 'There are 82 peanuts left in the jar.',
 'Ambulance ride:1700$',
 'Mercedes and Davonte ran 32 km in total.',
 'Nguyen still needs 49 feet of fabric.',
 'Each beaker holds 14 mL of solution.',
 'If we let x be the number of bands that Aira had, then Samantha had x + 5.',
 'Since Aira had 1 fewer band than Joe, then Joe had x + 1.',
 'She makes her husband 6 cakes a year.',
 "Let's say the number of fish that was in the tank before was x",
 'If you caught 4 fewer fish than the number that was there, then you caught x-4',
 'His walk through the store was twice the distance of his run, so his walk was 2X.',
 'Since he has 16 slices, Shane makes 16 sandwiches.',
 'So the price of an adult ticket is X*2.',
 "E = Evan's earnings",
 'Therefore, the lowest amount she can pay is $6, as this is cheaper than the $7 price for a 16 oz package.',
 'If 50% of the marbles are blue, and 25% of them are red, then the remaining 25% must be either green or yellow.',
 'Since each game was worth 10 marbles, Reggie has lost 1 game',
 'So the cost of a child ticket is X-6.',
 'Since 3>2, Adrian purchases choice B.',
 'The answer is therefore 3.',
 'The entree costs D+5 dollars',
 'Felicity used 23 gallons of gas for her trip.',
 'Kayla picked 10+4x apples',
 "If the number of males going to the meeting is twice the number of females, we'll assume the number of females is x and the number of males is 2x.",
 'There are C cans of cherry soda in the cooler.',
 'There are twice as many cans of orange pop, so there are 2C cans of orange pop in the cooler.',
 'Kwame and Conner studied 143 minutes more than Lexia.',
 'They end up buying 27 vegetables total, and from those 27, 15 of them were corn.',
 'If Rena will be 5 years older than Pam in 10 years, this means they have a 5 year age gap.',
 'The original price is x.',
 'Lawrence would work 5 hours each of the 7 days in a week.',
 'He has x+4 dimes.',
 'The dimes are worth 10 * (x+4)',
 'Therefore, Yanna kept 36 apples.',
 'The average temperature was -7 degrees Fahrenheit.',
 'He must average 90 miles per hour to drive the remaining 90 miles in 1 hour',
 'A century has 100 years, and if Gideon has as many marbles as the number of years in a century, he has 100 marbles.',
 'Birgit would take 48 minutes to travel 8 kilometers.',
 'Hannah ran 2089 meters farther on Monday than Wednesday and Friday.',
 'On the first day, they started off doing one round of 30 minutes.',
 'Since 25>20, this means Jenny should choose neighborhood B.',
 'Thus, the cost of the earrings would be 3x.',
 'Let’s use p for the number of feet in Mark’s pond',
 'The show runs from 2:00 pm to 2:30 pm so that is 30 minutes.',
 'Green grapes = G',
 'There are 67 red grapes.',
 'On the first day, he ate half the gummy worms, so he had G / 2 gummy worms.',
 'Dad gave Olaf 10 toy cars,',
 'Auntie gave Olaf 6 toy cars,',
 "If Tina's classroom has as many students as Maura's then T=M",
 '$125 is the balance Megan started with, so her final balance is 100% of the starting balance.',
 'First Year:40 apples',
 'Sam is (1/2)x',
 'At 2 pm there are 2 inches of rain in the tank.',
 'The cats weigh 5 kg more than the puppies.',
 'Cristobal read 1423 more pages than Beatrix.',
 'The next roll will be his 11th roll.',
 '8 gallons of water added during the first hour',
 'The winner ate 15 ounces in total because 15 > 14',
 'Cape May has 2x-8 shark sightings',
 'Amare still needs 59 feet of fabric.',
 'Kayla picked (1/4)x apples',
 'In the first month he can run 3 miles.',
 'He needs to start training 5 months ahead of time because 24 < 26.3 and 48>26.3.',
 "Sarah's name has 5 letters, so the first number to add is 5.",
 'Antonia will have 350 pills left after 2 weeks.',
 'The average temperature was -12 degrees Fahrenheit.',
 "Let's say the third number is x.",
 'Building C has 59 floors.',
 'There would be 44 cups of flour and sugar combined for 8 batches of cookies.',
 'Eliza is 68 inches tall.',
 'The second frog:2x',
 'Vlad is 41 inches taller than his sister.',
 "So, Leonard's age is x - 4.",
 "And Jerome's age is 2x.",
 'The six-foot length is long enough because 12 > 10',
 'The cheapest rope to buy is the 6-foot rope because 5 < 6.25',
 'Zane picked up 62 pounds of garbage.',
 'Because 200 < 220 Lola wins.',
 'The nth term of the sequence for the basketball players taking cookies in 2n-1.',
 '3x is the number of donuts for Beta.',
 '3x + x is the number of total donuts for Beta and Gamma.',
 'With the 4 that were already ripe, there will be 14 peaches that have ripened.',
 'He averaged working 190 hours per month.',
 "If Carole can read at Anna's same speed then her speed is also 1 page per min",
 'There are 573 gold, silver, and black balloons in total.',
 'He can only make 16 milkshakes because 16 < 18',
 'Telegraph is 150 km longer than Pardee Road.',
 'Each scoop of ice cream cost 5 dollars',
 'Frank spent 1/5*X on groceries.',
 'Frank spent 1/4*(X-1/5*X) on a magazine.',
 'After Jeff comes by, Tim has x-6 cans left.',
 'Tim buys another (x-6)/2 cans.',
 'The gets 85 ounces in food because 85 > 84',
 'On the first day, she will do 10 push-ups.',
 'So the price of one adult ticket is X*2.',
 'Since there are more green stones than grey stones, and the white and black pile have the same percentage, and there are more white stones than black stones, that means there are 60 percent white stones in the first pile.',
 'So Gabriel is X-3 years old.',
 'Justine colored on 245 pieces of paper.',
 'days.',
 'The Bertolli Farm grows 5200 fewer onions than tomatoes and corn.',
 'Bass:32',
 'Nicolai ate 6 pounds of peaches.',
 'Thomas will need 55 chairs for the party.',
 'Each raised bed is 8 feet long, the same as the planks, so the long sides of the beds will each be 1 plank long.',
 "Jenny's bedroom is M+60 square feet.",
 "Martha's bedroom is 120 square feet.",
 'At the beginning, Jacob had 8 fish',
 'Each artichoke makes 5/3 ounces of dip because there are 3 artichokes per 5 ounces',
 'All the dogs with 4 legs had 4N paws.',
 'Ivan has 36 apples leftover.',
 'Toby: 2x-10',
 'On Tuesday, Anna ate 4 apples.',
 'On Monday he picks 100 oranges.',
 'The 200 ounce bottle is the cheapest per ounce because .05 < .08 < .1 < .125',
 'The blueberries are cheaper because 13.5 < 14',
 "We learn here then that Paul will get a higher reward for obtaining A grades ($20) than getting A+ grades ($15) as long as he's able to score at least two A+.",
 'Assuming Paul can get two A+ and eight A in his next scorecard his total payout would be 2*$15 + 8*$20',
 'The six throws were 20 feet, 30 feet, 34 feet, 16 feet, 32 feet, and 37 feet, and of these numbers, 37 feet was the highest.',
 'Each friend now has 39 balloons.',
 'Each truck will carry 160 containers of oil.',
 'Together, Lena and her brother played 437 minutes of video games.',
 'Together they ate 13 apples.',
 'A dye treatment takes twice as long, so it takes 2H.',
 'There are 44 apples in the bowl.',
 "Let's say Arielle's age is x",
 "The sum of Elvie's age and Arielle's age is 10+x",
 'The product of their ages is 10*x',
 "The value of x, which is Arielles's age, is 11",
 "L = Lottie's earnings",
 'The grocery store sells 1 cup packages of berries for $2.00 a pack.',
 'So, there are (x + 1) $20 bills.',
 'Therefore, there are 2 $10 bills.',
 'Joel donated twice as many toys, so he donated 2T toys.',
 'The best bucket gives three points because 3 > 2',
 'One packet of floss is enough because 35 > 30',
 'The increase in productivity of the Albaszu machine was one and a half, which is 1 1/2 or 3/2.',
 'They used 28 containers.',
 '64 pieces of bread are needed for those sandwiches.',
 'Sally sold 60 boxes on Saturday.',
 'Steve has 2x berries',
 'The remaining buckets are thus the 11, 12, and 16 ounce buckets.',
 'Celine collected 2*x erasers.',
 'Henri drove 305 miles farther.',
 'Since Rick is looking for categories with 25 books in each, he accomplishes this by the 4th step.',
 'Hence, Jed will have a total of 40 cards in 4 weeks.',
 'His new TV is 1,536 square inches.',
 'Comparing 2, 5 and 6 shows that 6 is the greatest difference',
 'There would be C-1 cookies.',
 'Hannah must beat the student who got a 38 because 38 > 37',
 '25 cents is equal to 1 quarter.',
 'Second day: x/2',
 'Third day: 3x',
 'There are A+2 pears.',
 'There are (A+2)+3 pears.',
 'There are 4 apples.',
 'Indira played cricket for 812 minutes.',
 'Maddy needs to take 5 classes per semester',
 'The third issue is 4 pages longer, so it is P + 4 pages.',
 'He can make 48 pickles because 48 < 60',
 'Mirella read 890 more orange pages than purple pages.',
 "We don't know Yasmin's number of children yet, but let's represent it as Y.",
 'In the 3 cups needed to make one liter of lemonade, the fraction representing the cups of sugar needed is 1/3.',
 'They will need to plan to study 4 days to allow for all the time they need.',
 'The first lesson is free.',
 'He then had 9 remaining lessons where he had to pay for every other one.',
 'Dad took 27 minutes to vacuum upstairs.',
 'Bogan gave the beetles 10 maggots in the first feeding',
 'There were 30 women working for the company before the new hires'
 ]